---
name: Say hello
description: An action to say hello
inputs:
  workspace:
    description: 'Github workspace'
    required: true
  title:
    description: 'Title of the Pull Request'
    required: true
runs:
  using: node12
  main: index.js